version: '3'
services:
    mysql:
        container_name: mysql
        image: mysql:8.0-debian
        restart: unless-stopped
        volumes:
          - ./mysql:/var/lib/mysql:delegated
        ports:
          - 3306:3306
        environment:
          TZ: 'America/Fortaleza'
          MYSQL_DATABASE: aula_mysql
          MYSQL_USER: aula_mysql
          MYSQL_PASSWORD: aula_mysql
          MYSQL_ROOT_PASSWORD: aula_mysql

    dbgate:
        image: dbgate/dbgate
        container_name: dbgate
        restart: unless-stopped
        ports:
          - 8010:3000
        volumes:
          - .dbgate:/root/.dbgate
